# TENSOR

In [2]:
import numpy as np

## 0-D(Scalers)

In [3]:
a=np.array(2)

In [4]:
a

array(2)

In [5]:
a.ndim

0

## 1-D(Vectors)

In [6]:
b=np.array([1,2,3,4,5])

In [7]:
b

array([1, 2, 3, 4, 5])

In [8]:
b.ndim

1

## 2-D(Matrices)

In [13]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
c.ndim

2

## 3-D(N-D Tensor)

In [15]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [16]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [17]:
d.ndim

3

## 4-D

In [18]:
e=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])

In [19]:
e

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [21]:
e.ndim

4

## 5-D

In [22]:
f=np.array([[[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]],
            [[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]]])

In [23]:
f

array([[[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]],



       [[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]]])

In [24]:
f.ndim

5

## 6-D

#### Collection of 5-D Tensors